language: node_js
os: linux
node_js:
  - 12.14.1
before_install:
  - npm install -g yarn
branches:
  only:
    - master
before_deploy:
  - rm -rf node_modules
  - zip -r latest
  - mkdir -p deploy
  - mv latest.zip deploy/latest.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: s3forcode
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: yuzin9712/Capstone02
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: s3forcode
    key: latest.zip
    bundle_type: zip
    application: capcodedeploy
    deployment_group: capstone
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: yuzin9712/Capstone02
      branch: master
notifications:
  email:
    recipients:
      - dbwls97@ajou.ac.kr
